on: [push]
name: 🧿🧿Azure bicep deploy
env:
  resourceGroupName: rgoyvind1201
  bicepfilePath: ./main.bicep
  resourceGroupLocation: WestUS 
  storageAccountName: cloudresumeoyvind222
  outputFilePath: ./main.json
  deployName: oyvinddeploy131

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: ${{  env.bicepfilePath }}
          outputFilePath: ${{ env.outputFilePath }}
      - name: loginazure🧿💙
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploybicep2
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{env.resourceGroupName}}
          template: ${{ env.outputFilePath }}
          failOnStdErr: false

      #- name: deploybicep💪🐝
      #  uses: azure/cli@v1   
      #  with:
      #    inlineScript: |
      #      az deployment sub create  \
      #      --name ${{env.deployName}} \
      #      --location ${{env.resourceGroupLocation}} \
      #      --template-file ${{env.bicepfilePath}} \
          
   #second build starts       
  test-deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: azure/login@v1
       with: 
           creds: ${{ secrets.AZURE_CREDENTIALS }}

     - name: create folder
       uses: azure/CLI@v1
       with:
         inlineScript: |
          az storage container create -n $web --account-name ${{env.storageAccountName}}
               
     - name: Upload to blob storagebl
       uses: azure/CLI@v1
       with:
         inlineScript: |
             az storage blob upload-batch --account-name ${{env.storageAccountName}} --auth-mode key --pattern *.html --overwrite true -d '$web' -s .
             az storage blob upload-batch --account-name ${{env.storageAccountName}} --auth-mode key --pattern *.css --overwrite true -d '$web' -s .
             az storage blob upload-batch --account-name ${{env.storageAccountName}} --auth-mode key --pattern *.js --overwrite true -d '$web' -s .
     - name: Purge CDN endpoint
       uses: azure/CLI@v1
       with:
         inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "cdnofzpcph7h4irqa4" --name "finsrudcloud2" --resource-group ${{env.resourceGroupName}}
      ##Azure logout
     - name: logout
       run: |
            az logout
       if: always()