on:
    push:
        branches: [ main ]

name: Azure CloudResumeIAC bui1ld

env:
  RESOURCE_GROUP: rg-bicep-github-action-1
  WEBAPP_NAME: BICEP_web_1


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: az bicep deploy
      working-directory: '${github.workspace}./'
      run: |
        az deployment group create --what-if --template-file ./main.bicep
  
  deploy:
    name: 'bicep deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: azure azure/login
        uses: azure/login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: az bicep deploy
        working-directory: '${{github.workspace}}./'
        run: | 
            az deployment group create  --template-file ./main.bicep



